In [60]:
# Descobrindo a 'criptografia' do csv

import chardet

with open('./BasesLixoSP/coletaLixoSP_2013.csv', 'rb') as f:
    result = chardet.detect(f.read())
    print(result['encoding'])

ISO-8859-1

In [61]:
import pandas as pd
import numpy as np


ano = 20


df = pd.read_csv(f'./BasesLixoSP/coletaLixoSP_20{ano}.csv', encoding='ISO-8859-1', sep=';')


# sep=';' --> essencial para separar os valores, vulgo delimitador
# encoding='ISO-8859-1' --> precisa 'descriptografar' para ler corretamente os dados

In [62]:
df.info()

colunas_converter = [f'{mes}/{ano}' for mes in ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']]

df.columns = df.columns.str.strip()



for mes_coluna in colunas_converter:
    df = df.fillna(0)
    df[mes_coluna] = df[mes_coluna].fillna('0').astype(str).str.strip().replace(r'^\s*$', '0', regex=True).str.replace(',', '.').str.replace('-', '0').astype(float)

df.rename(columns={"TIPO DE RES√ñDUO": "Tipo_Residuo", '√Ø¬ª¬øTipo de res√É¬≠duo - Toneladas':'Tipo_Residuo',  'TIPO DE RES√çDUO': 'Tipo_Residuo', 'TIPO DE RES√Ø¬ø¬ΩDUO': 'Tipo_Residuo', 'Tipo de Res√≠duo - Toneladas': 'Tipo_Residuo', 'Tipo de res√Ø¬ø¬Ωduo - Toneladas': 'Tipo_Residuo', 'Tipo de res√≠duo - Toneladas': 'Tipo_Residuo', 'Tipo de residuo - Toneladas': 'Tipo_Residuo', 'TIPO DE RESDUO':'Tipo_Residuo', f"TOTAL 20{ano}": f"total_20{ano}", f'20{ano}': f'total_20{ano}'}, inplace=True)

df.columns = df.columns.str.lower().str.strip()
df['tipo_residuo'] = df['tipo_residuo'].str.replace('TOTAL', 'total geral')
df['tipo_residuo'] = df['tipo_residuo'].str.lower().str.title()

# tratamento de anos espec√≠ficos
if ano >= 20 :
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)
else:
    df[f'total_20{ano}'] = df[f'total_20{ano}'].fillna('0').str.strip().replace(r'^\s*$', '0', regex=True).str.replace('.', '').str.replace(',', '.').str.replace('-', '0').astype(float)
    df[f'total_20{ano}'] = df[colunas_converter].sum(axis=1)


df['tipo_residuo'] = df['tipo_residuo'].str.strip()

if ano <= 18:
    df = df[df['tipo_residuo'] != 'Total Geral']
df = df[df['tipo_residuo'] != '(Vazio)']

if ano == 17:
    df = df.drop(columns='unnamed: 14')
if ano == 24:
    df = df.drop(columns='unnamed: 13')

    
display(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tipo de res√≠duo - Toneladas  33 non-null     object
 1   jan/20                       33 non-null     float64
 2   fev/20                       33 non-null     float64
 3   mar/20                       33 non-null     float64
 4   abr/20                       31 non-null     float64
 5   mai/20                       33 non-null     float64
 6   jun/20                       33 non-null     float64
 7   jul/20                       33 non-null     float64
 8   ago/20                       33 non-null     float64
 9   set/20                       33 non-null     float64
 10  out/20                       33 non-null     float64
 11  nov/20                       32 non-null     float64
 12  dez/20                       33 non-null     float64
dtypes: float64(12), object(1)
memory usage: 3.5+ KB

,tipo_residuo,jan/20,fev/20,mar/20,abr/20,mai/20,jun/20,jul/20,ago/20,set/20,out/20,nov/20,dez/20,total_2020
0,Domiciliar,317.183,301.322,317.174,276.684,276.721,303.261,303.903,297.064,300.749,304.548,288.071,332.637,3619.317
1,Entulho Mecanizado,11.783,10.175,12.628,11.080,10.858,12.920,12.996,9.697,8.713,9.254,7.883,7.443,125.430
2,Residuos De Ecoponto,32.876,34.225,36.639,29.838,28.588,29.419,33.996,29.855,31.316,31.237,25.779,27.760,371.528
3,Diversos,34.419,34.304,38.879,34.545,33.554,35.958,34.066,27.748,28.413,28.761,27.706,29.169,387.522
4,Esgoto,16.050,14.110,18.095,17.825,19.127,17.875,22.443,18.649,23.443,18.184,12.851,14.864,213.516
5,Residuos De Piscinao,12.983,19.365,17.045,17.199,16.207,18.534,20.490,14.844,14.083,15.415,13.485,13.779,193.429
6,Residuos De Corregos,17.766,8.768,19.418,19.156,17.993,20.414,19.061,18.753,22.086,22.900,32.003,38.609,256.927
7,Varricao,4.527,6.423,4.381,3.663,3.870,4.850,6.232,6.370,7.762,7.598,6.998,8.874,71.548
8,Seletiva,8.425,7.271,8.039,8.058,7.459,7.894,7.986,7.689,7.811,7.930,7.283,8.620,94.465
9,Feira Livre,6.562,7.013,7.180,6.200,6.578,7.144,6.561,5.951,5.645,5.859,5.277,5.836,75.806
10,Entulho Manual,1.249,1.539,1.933,1.682,1.896,2.323,2.957,2.699,2.653,3.029,1.465,1.380,24.805
11,Poda,5.236,5.139,5.959,5.320,4.532,5.679,6.123,5.126,5.078,5.051,5.446,6.174,64.863
12,Gg Saude,2.711,2.589,2.727,2.488,3.017,3.292,3.476,3.395,3.251,3.308,3.281,3.334,36.869
13,Rejeito-Cmt Cmj,1.629,1.390,1.175,1.662,1.380,1.719,1.886,1.525,1.688,1.619,1.248,1.641,18.562
14,Residuos De Boca De Lobo,1.321,1.574,1.852,1.289,951.000,1.195,1.409,1.407,1.419,1.218,853.000,943.000,2759.684
15,Pg Saude,729.000,691.000,734.000,540.000,597.000,710.000,823.000,803.000,824.000,861.000,806.000,837.000,8955.000
16,Remocao Residuos Descartados,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17,Residuos Patio Compostagem,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
18,Rejeito,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
19,Entulho Apreendido,10.000,8.000,15.000,0.000,12.000,0.000,0.000,0.000,0.000,0.000,10.000,0.000,55.000
20,Madeira,2.868,3.152,2.939,1.871,2.302,3.953,4.745,5.243,5.137,5.122,5.404,6.389,49.125
21,Animais,2.000,1.000,3.000,3.000,2.000,1.000,1.000,3.000,1.000,1.000,2.000,2.000,22.000
22,Varricao Mecanizada,452.000,518.000,350.000,413.000,377.000,511.000,460.000,554.000,442.000,554.000,529.000,493.000,5653.000
23,Alim Vencidos,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
24,Material Apreendido,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,353.000,322.000,675.000
25,Residuo De Acumulador,29.000,1.000,11.000,0.000,4.000,2.000,61.000,52.000,65.000,24.000,0.000,14.000,263.000
26,Residuo De Desfazimento,0.000,0.000,0.000,0.000,0.000,61.000,47.000,394.000,40.000,18.000,104.000,17.000,681.000
27,Equipe De Eventos Especiais E Operacoes De Eme...,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000
28,Residuo Ecoponto - Entulho,5.466,1.056,1.005,2.829,2.931,9.486,11.066,10.261,8.640,9.572,10.718,9.182,82.212
29,Entulho Do Predio,0.000,0.000,10.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,10.000
30,Limpeza Urbana,0.000,0.000,4.000,0.000,0.000,7.000,0.000,0.000,0.000,0.000,0.000,0.000,11.000
31,Residuos De Ecoponto - Diversos,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.244,3.000,196.000,137.000,120.000,457.244
32,Total Geral,484.276,460.635,498.195,442.344,438.957,487.207,500.790,469.325,479.258,482.262,457.690,518.438,5719.377

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tipo_residuo  33 non-null     object
 1   jan/20        33 non-null     float64
 2   fev/20        33 non-null     float64
 3   mar/20        33 non-null     float64
 4   abr/20        33 non-null     float64
 5   mai/20        33 non-null     float64
 6   jun/20        33 non-null     float64
 7   jul/20        33 non-null     float64
 8   ago/20        33 non-null     float64
 9   set/20        33 non-null     float64
 10  out/20        33 non-null     float64
 11  nov/20        33 non-null     float64
 12  dez/20        33 non-null     float64
 13  total_2020    33 non-null     float64
dtypes: float64(13), object(1)
memory usage: 3.7+ KB

In [63]:
# visualiza√ß√£o data_type
print(df.columns)

Index(['tipo_residuo', 'jan/20', 'fev/20', 'mar/20', 'abr/20', 'mai/20',
       'jun/20', 'jul/20', 'ago/20', 'set/20', 'out/20', 'nov/20', 'dez/20',
       'total_2020'],
      dtype='object')

In [64]:
df.to_excel(f'./BaseLimpo/20{ano}_coleta_tipos_residuos.xlsx', index=False)